### PR TITLE
Added a Danish translation

### PR DESCRIPTION
**Pull request by Saturate**
I added a Danish translation. Nothing more, nothing less.

### CODE REVIEW

**Comment by dersphere** [comment]
Could you also translate addon.xml?

**Comment by Saturate** [comment]
Ah, sure did not notice that. I'll look in to it.

**Comment by dersphere** [comment]
ping :)

**Comment by Saturate** [comment]
Thanks for the ping, I forgot about this...  I'll look in to it - again!

**Comment by Saturate** [comment]
@dersphere ping back! :)

**Comment by dersphere** [comment]
Thanks for the ping back! :)

**Pull request merged**
